### PR TITLE
LinkedList problems, solution in C++

### LINKED ISSUE #80: 07 Linked List --> 1. Finding middle element in a linked list
Given a singly linked list of N nodes. The task is to find the middle of the linked list. For example, if given linked list is 1->2->3->4->5 then the output should be 3.
If there are even nodes, then there would be two middle nodes, we need to print the second middle element. For example, if given linked list is 1->2->3->4->5->6 then the output should be 4.

Example 1:

Input:
LinkedList: 1->2->3->4->5
Output: 3 
Explanation: 
Middle of linked list is 3.
Example 2: 

Input:
LinkedList: 2->4->6->7->5->1
Output: 7 
Explanation: 
Middle of linked list is 7.
Your Task:
The task is to complete the function getMiddle() which takes a head reference as the only argument and should return the data at the middle node of the linked list.

Expected Time Complexity: O(N).
Expected Auxiliary Space: O(1).

Constraints:
1 <= N <= 5000

### LINKED ISSUE #83: 07 Linked List --> 4. Reverse a Linked List
Given a linked list of N nodes. The task is to reverse this list.

Example 1:

Input:
LinkedList: 1->2->3->4->5->6
Output: 6 5 4 3 2 1
Explanation: After reversing the list, 
elements are 6->5->4->3->2->1.
Example 2:

Input:
LinkedList: 2->7->8->9->10
Output: 10 9 8 7 2
Explanation: After reversing the list,
elements are 10->9->8->7->2.
Your Task:
The task is to complete the function reverseList() with head reference as the only argument and should return new head after reversing the list.

Expected Time Complexity: O(N).
Expected Auxiliary Space: O(1).

Constraints:
1 <= N <= 104

### PR DESCRIPTION
**Pull request by Amisha328**

### CODE REVIEW

**Comment by Amisha328** [comment]
Hi, @FazeelUsmani 
Please check #85 and let me know if any update is required.

**Review by FazeelUsmani — APPROVED** [review]
Thank you for the contribution, @Amisha328

**Review by FazeelUsmani — CHANGES_REQUESTED** [review]
Can you rename the file as 01_middleElement.cpp so to remain in serial?
07 Linked LIst is fine

**Comment by Amisha328** [comment]
> Can you rename the file as 01_middleElement.cpp so to remain in serial?
> 07 Linked LIst is fine

Yes, sure.

**Comment by Amisha328** [comment]
Hi, @FazeelUsmani
Please check now and let me know if any update is required.

**Comment by Amisha328** [comment]
Hi, @FazeelUsmani
Please check the 04 problems solution in #85 and let me know if any update is required.

**Review by FazeelUsmani — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
